# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Savor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Savor
  pod 'FTPopOverMenu_Swift'
  pod 'SearchTextField'
  pod 'UITextView+Placeholder'
  pod 'Cosmos'
  
  pod 'DCKit'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SwifterSwift'
  
  pod 'Permission/Camera'
  pod 'Permission/Photos'
  
  pod 'CDYelpFusionKit'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
end
