# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Savor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Savor
  pod 'KUIPopOver'
  pod 'KMPlaceholderTextView'
  pod 'Cosmos'
  pod 'MagazineLayout'
  pod 'ImageSlideshow'
  pod 'PullToRefreshKit'
  pod "ImageSlideshow/SDWebImage"
  pod 'InputBarAccessoryView'
  
  pod 'DCKit'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SwifterSwift'
  pod 'SnapKit'
  
  pod 'arek/Photos'
  pod 'arek/Camera'
  pod 'arek/Location'
  
  pod 'SwiftLocation'
  
  pod 'CDYelpFusionKit'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
  pod 'GeoFire'
  
  pod 'GooglePlaces'
  
end
